#!/bin/sh

git pull

NOSAN=
BONUS=

for i in $@
do
	if [ $i == "nosan" ]
	then
		NOSAN="nosan"
	fi
	if [ $i == "b" ]
	then
		BONUS="bonus"
	fi
done

make ${BONUS}${NOSAN}

if [ $? -ne 0 ]
then
	echo -e "\ncompilation error kkkkkkkkkkkkkkkkkkkk"
else
	echo "./tester $@ 2>myleaks.txt"
	./tester $@ 2>myleaks.txt
fi
